Fixed wait function with a default duration
duration was not initialized and caused this tracback:
UnboundLocalError: local variable 'duration' referenced before assignment